{
    'name': 'Odoo Shopify Connector',
    'summary': 'Odoo Shopify Connector',
    'version': '18.0.1.0.0',
    'sequence': 6,
    'description': """Odoo Shopify Connector""",    
    'author': '',
    'category': 'Sales',
    'maintainer': '',
    'website': '',
    'license': 'LGPL-3',
    'depends': ['base', 'web', 'sale_management', 'purchase', 'stock', 'contacts', 'delivery', 'hr_expense'],
    'external_dependencies': {
        'python': ['ShopifyAPI'],
    },
    'data': [ 
        'security/ir.model.access.csv',
        'wizard/sale_order_instance.xml',        
        'wizard/customer_import.xml',        
        'wizard/product_instance.xml',        
        'wizard/locations_import.xml',        
        'wizard/inventory_update.xml',        
        'wizard/generate_invoice.xml',   
        'wizard/generate_refund.xml',   
        'wizard/shopify_order_actions.xml',   
        'wizard/message_wizard.xml',                     
        'views/shopify_product.xml',
        'views/shopify_images.xml',
        'views/shopify_instance.xml',
        'views/shopify_sale_order.xml',
        'views/shopify_customer.xml',
        'views/shopify_tax.xml',
        'views/shopify_account_move.xml',
        'views/shopify_product_category.xml',
        'views/shopify_locations.xml',
        'views/menu.xml',
        'views/cron.xml',
    ],
    'images': ['static/description/banner.png'],
    'pre_init_hook': '_pre_init_collect',
    'uninstall_hook': '_uninstall_collect',
    'installable': True,
    'assets': {
        'web.assets_backend': [
            'mt_odoo_shopify_connector/static/src/scss/shopify_graph_widget.scss',
            'mt_odoo_shopify_connector/static/src/**/*.js',
            'mt_odoo_shopify_connector/static/src/**/*.xml',             
        ],
    },    
}
